{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "fa0d35ad_2a97bdf8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1380269
      },
      "writtenOn": "2021-01-26T02:06:44Z",
      "side": 1,
      "message": "Thanks!",
      "revId": "bb773dd4d5e753089a0557229e72e877658a31ef",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "e3c6ebb1_b71946e8",
        "filename": "vendor_snapshot/update.py",
        "patchSetId": 4
      },
      "lineNbr": 457,
      "author": {
        "id": 1291338
      },
      "writtenOn": "2021-01-26T23:39:03Z",
      "side": 1,
      "message": "We should explicitly print an error here, right? bpeckham@",
      "range": {
        "startLine": 455,
        "startChar": 0,
        "endLine": 457,
        "endChar": 0
      },
      "revId": "bb773dd4d5e753089a0557229e72e877658a31ef",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}